Gh test
sudiptob2/leet-easy pull request #46
Opened 2022-10-06 22:27 UTC by nilesh05apr

Implement a github action to check unit tests #33

Fresh PR for the above task.

2022-10-08 03:41 UTC, sudiptob2 reviewed
We need several improvements in this action, Let's work on it step by step. :blush:

2022-10-08 03:41 UTC, sudiptob2 commented on .github/workflows/test.yml
> +      - name: Install dependencies
we need to cache the dependencies for a faster run. Can you do some research and implement this caching mechanism, please?
Here is an example : [caching dep example](https://github.com/sudiptob2/cf-stats/blob/befabb28dfb41e34a5151fad1898842152c3cb33/.github/workflows/test.yml#L23)

2022-10-11 03:22 UTC, sudiptob2 reviewed
Thanks :pray: 
Now we have to run `check.sh` script instead of running `pytest` directly in the workflow. I have implemented the required checks in that script, please take a look.

Also, I could not check the cache hit, could you please double-check and make sure caching is working :blush:

2022-10-11 12:10 UTC, nilesh05apr commented
@sudiptob2 i have manually re checked, all jobs are running fine and cache hit also successful. Now i need to work on running the bash script in the workflow.
Please check and review the progress.

2022-10-11 12:25 UTC, sudiptob2 requested changes
we don't need to run pytest, its already inside the `check.sh`

2022-10-11 12:25 UTC, sudiptob2 commented on .github/workflows/test.yml
> +          python3 -m pytest
```suggestion
```

2022-10-11 12:32 UTC, sudiptob2 commented
@nilesh05apr I think if you could use `pipenv` and install dependencies using `Pipfile` then you need not to install these `dev dependencies` manually.
Because these dev dependencies are not mentioned in the `requirements.txt`, it's a hassle to install them one by one in the `ghithub actions` manually.
if you use `pipenv` then you can just do
```
run: pipenv install --dev --verbose
```
see this [github action](https://github.com/chkware/cli/blob/main/.github/workflows/linux-run-tests.yml) for example.

2022-10-11 20:35 UTC, nilesh05apr commented
@sudiptob2 can you please suggest any fix? now caching is also failing.

2022-10-12 03:59 UTC, sudiptob2 commented
One thing I can understand about caching is that the cache key is not right. As you are using a matrix of python, you have to append the python version to make those cache keys unique. Also, you have to remove windows OS, because things are different there.
Apart from that remove these lines
```bash
      # Run tests
      - name: Test
        run: |
          python3 --version
          python3 -m pip install pytest pytest-mock flake8 mypy requests
          python3 -m pytest 
```
these are not necessary because, the `check.sh` already doing these tests.

2022-10-12 04:14 UTC, nilesh05apr commented
@sudiptob2  i updated the code but the problem for check.sh remains same.

2022-10-12 04:23 UTC, sudiptob2 reviewed
seems better now, But we still have errors right?
below checks might help.
**caching** : run the action multiple time and confirm that the cache is working
**check.sh**: I can see this script is failing, I suppose, I was using `python` as interpreter may be `python3` is needed. Also maybe we need to install the missing stubs

2022-10-12 04:25 UTC, nilesh05apr commented
for the caching part i will re run the jobs as many times as required but for the check.sh file i am unable to find and helpful resource.

2022-10-12 04:45 UTC, sudiptob2 reviewed
In my opinion, these changes are goin to the wrong direction, your previous commit was OK, just it might need to install some stub packages, you can revert these changes and I will try to check it myself and you know If I can fix it.

2022-10-12 04:48 UTC, nilesh05apr commented
the problem is caching is also not working properly i have checked several times, can you please comment?

2022-10-12 04:50 UTC, sudiptob2 commented
> the problem is caching is also not working properly i have checked several times, can you please comment?

Ok, just keep this PR at the previous commit, I will test and update you if I can find anything. You can always do experiments in a separate branch right.

2022-10-12 04:52 UTC, nilesh05apr commented
sure that i can do, i will create a new branch and try experimenting. Thanks

2022-10-12 16:37 UTC, sudiptob2 commented
I have implemented/fixed the workflow, see [here](https://github.com/sudiptob2/leet-easy/blob/experiment/action/.github/workflows/test.yml)

you can update your PR with the [this code](https://github.com/sudiptob2/leet-easy/blob/experiment/action/.github/workflows/test.yml)

2022-10-13 01:36 UTC, nilesh05apr commented
Thanks so much @sudiptob2 for the help. I have implemented the changes and have ensured everything is running smoothly.

2022-10-13 04:12 UTC, nilesh05apr commented
@ can you please review and merge the pull request. Thank you

2022-10-13 04:39 UTC, sudiptob2 reviewed
There are a few small differences from what I implemented [here](https://github.com/sudiptob2/leet-easy/blob/experiment/action/.github/workflows/test.yml)
I might have miss a few thing while reviewing this, I would suggest you copy and paste the entire code from [here](https://github.com/sudiptob2/leet-easy/blob/experiment/action/.github/workflows/test.yml) to your file

2022-10-13 04:39 UTC, sudiptob2 commented on .github/workflows/test.yml
> +      - name: Python version
add a space before this line

2022-10-13 04:39 UTC, sudiptob2 commented on .github/workflows/test.yml
> +  - pull_request
```suggestion
```

2022-10-13 04:39 UTC, sudiptob2 commented on .github/workflows/test.yml
> +  - push
```suggestion
```

2022-10-13 04:39 UTC, sudiptob2 commented on .github/workflows/test.yml
> +
```suggestion
  pull_request:
    types: [ready_for_review]
```

2022-10-13 04:39 UTC, sudiptob2 commented on .github/workflows/test.yml
> +          path: ./.venv
```suggestion
          path: .venv
```

2022-10-13 04:51 UTC, nilesh05apr commented
@sudiptob2 i have copy-pasted the code XD. please review the changes

2022-10-13 04:54 UTC, sudiptob2 approved these changes
seems OK

2022-10-13 05:04 UTC, nilesh05apr commented
Thank you @sudiptob2 i had great experience working on this issue.

2022-10-13 05:06 UTC, merged