Create PULL_REQUEST_TEMPLATE.md
sudiptob2/leet-easy pull request #52
Opened 2022-10-16 18:56 UTC by hari-ajidesh

Closes #51

2022-10-16 19:11 UTC, hari-ajidesh commented
Please add the hacktoberfest-accepted label to this issue

2022-10-17 04:41 UTC, sudiptob2 commented
Thanks for adding a lovely PR template. However, I actually want the template mentioned in the description of issue #52. Can you update :pray:

2022-10-17 05:01 UTC, hari-ajidesh commented
PR template has been updated as requested in #51 . Do look into it

2022-10-17 05:09 UTC, sudiptob2 requested changes

2022-10-17 05:09 UTC, sudiptob2 commented on .github/PULL_REQUEST_TEMPLATE.md
> +# Checklist:
```suggestion
### Checklist:
```

2022-10-17 05:09 UTC, sudiptob2 commented on .github/PULL_REQUEST_TEMPLATE.md
> +# Description
```suggestion
### Description
```

2022-10-17 05:09 UTC, sudiptob2 commented on .github/PULL_REQUEST_TEMPLATE.md
> +## Type of change
```suggestion
### Type of change
```

2022-10-17 06:27 UTC, sudiptob2 commented
Can you please incorporate the change that I requested? I think **heading 3** looks good than **Heading 1**

2022-10-17 06:28 UTC, sudiptob2 reviewed
Can you please incorporate the change that I requested? I think heading 3 looks good than Heading 1

2022-10-17 10:21 UTC, hari-ajidesh commented
Sorry for my mistake. I thought I incorporated them by clicking on "resolve conversation". Now they are updated

2022-10-17 10:35 UTC, sudiptob2 approved these changes

2022-10-17 11:01 UTC, merged